### PR TITLE
Upgrade btcec to v2

### PR DESCRIPTION
**Pull request by syr2bill**

### CODE REVIEW

**Review by sawsawsawsawsaw — APPROVED** [review]
review passed.

**Review by fbsobreira — APPROVED** [review]

**Comment by fbsobreira** [comment]
can you please sign commits and add `github.com/btcsuite/btcd/btcec/v2 v2.2.0` to go mod file? `go mod tidy`

**Comment by sawsawsawsawsaw** [comment]
> can you please sign commits and add `github.com/btcsuite/btcd/btcec/v2 v2.2.0` to go mod file? `go mod tidy`

@syr2bill Greatly appreciate your assistance in signing the commit. Thank you very much for your help.

**Comment by syr2bill** [comment]
@fbsobreira I have signed commits, please check

**Comment by ygcool** [comment]
Can merge this pr?

**Comment by aemet93** [comment]
Thank you very much for btcec update and merge.  Saved me days of struggling.

**Pull request merged**
